spring:
  redis:
    host: ${REDIS_HOST}
  cloud:
    gateway:
      routes:
        # 用户服务
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/manage/user/**, /api/judger/user/**, /api/user/**, /api/site/**
          filters:
            - StripPrefix=1
        # 鉴权服务
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/manage/auth/**, /api/judger/auth/**, /api/auth/**
          filters:
            - StripPrefix=1
        # 题库服务 / 检查点服务 / 标签服务 / 评测模板服务
        - id: problem-service
          uri: ${PROBLEM_SERVICE_URL}
          predicates:
            - Path=/api/manage/problem/**, /api/judger/problem/**, /api/problem/**, /api/manage/checkpoint/**, /api/judger/checkpoint/**, /api/checkpoint/**, /api/manage/tag/**, /api/judger/tag/**, /api/tag/**, /api/manage/judgetemplate/**, /api/judgetemplate/**
          filters:
            - StripPrefix=1
        # 提交服务
        - id: submit-service
          uri: ${SUBMIT_SERVICE_URL}
          predicates:
            - Path=/api/manage/submit/**, /api/judger/submit/**, /api/submit/**
          filters:
            - StripPrefix=1
        # WebSocket 服务
        - id: websocket-service
          uri: ${WEBSOCKET_SERVICE_URL}
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=1
        # 比赛
        - id: contest-service
          uri: ${CONTEST_SERVICE_URL}
          predicates:
            - Path=/api/manage/contest/**, /api/judger/contest/**, /api/contest/**
          filters:
            - StripPrefix=1
        # 文件系统
        - id: filesys-service
          uri: ${FILESYS_SERVICE_URL}
          predicates:
            - Path=/api/filesys/**
          filters:
            - StripPrefix=1


user-service.ribbon.listOfServers: ${USER_SERVICE_URL}
problem-service.ribbon.listOfServers: ${PROBLEM_SERVICE_URL}
auth-service.ribbon.listOfServers: ${AUTH_SERVICE_URL}
submit-service.ribbon.listOfServers: ${SUBMIT_SERVICE_URL}